services:
  - type: web
    name: cocoa-market-signals
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/dashboard/app_comprehensive.py
    envVars:
      - key: PORT
        value: 8002